apiVersion: v1
data:
  config.json: |
    {
    "listener": {
        "tcp": {
            "address": "[::]:8200",
            "cluster_address": "[::]:8201",
            "tls_cipher_suites": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA",
            "tls_disable": true,
            "tls_prefer_server_cipher_suites": true
        }
    },
    "storage": {
    "gcs": {
        "bucket": "vaultbck-01",
        }
    },
    "ui": true}
kind: ConfigMap
metadata:
  labels:
    app: gcs-vault
    chart: vault-0.14.1
    heritage: Tiller
  name: gcs-exciting-jaguar-vault-config

