apiVersion: v1
data:
  config.json: |
    {
    "listener": {
        "tcp": {
            "address": "[::]:8200",
            "cluster_address": "[::]:8201",
            "tls_cipher_suites": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA",
            "tls_disable": true,
            "tls_prefer_server_cipher_suites": true
        }
    },
    "storage": {
        "consul": {
            "address": "poc-consul:8500",
            "path" : "vault"
        }
    },
    "ui": true}
kind: ConfigMap
metadata:
  creationTimestamp: 2018-10-29T20:43:42Z
  labels:
    app: vault
    chart: vault-0.14.1
    heritage: Tiller
    release: exciting-jaguar
  name: exciting-jaguar-vault-config
  namespace: default
  resourceVersion: "12095097"
  selfLink: /api/v1/namespaces/default/configmaps/exciting-jaguar-vault-config
  uid: 5269b800-dbbb-11e8-b828-42010a8e00fe

